import {StyleSheet, Dimensions} from 'react-native';

const Height = Dimensions.get('window').height;
export const styles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    backgroundColor: '#FFF0E6',
    justifyContent: 'space-around',
    alignItems: 'center',
    // borderWidth: 5,
    borderColor: 'green',
    paddingVertical: Height / 10,
  },
  formContainer: {
    width: '100%',
    // borderWidth: 3,
    flex: 1,
    justifyContent: 'center',
    marginVertical: 10,
  },
  titleContainer: {
    marginVertical: 20,
  },
  title: {
    color: 'red',
    fontSize: 30,
    marginTop: 1,
    fontWeight: '800',
    textAlign: 'center',
  },
  formColumnContainer: {
    width: '90%',
    marginVertical: 15,
    marginHorizontal: 10,
    borderRadius: 10,
    padding: 5,
    elevation: 20,
    backgroundColor: 'white',
    height: 50,
    flex: 1,
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
  },
  inputText: {
    fontSize: 16,
    marginLeft: 15,
    width: '85%',
    color: 'black',
    height: 50,
  },
  formLogo: {marginLeft: 3},
  errorMessage: {color: 'red', fontSize: 15, fontWeight: '400', marginLeft: 15},
  bottomSheetMessage: {fontSize: 20, color: 'black', textAlign: 'center'},
  buttonStyle: {
    backgroundColor: '#EA4335',
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    marginTop: 20,
    alignSelf: 'center',
    elevation: 20,
    height: 50,
  },
  buttonTitleStyle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: 'bold',
    padding: 3,
    height: 44,
    textAlignVertical: 'center',
  },
  bottomInfoContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  forgotPassword: {
    fontSize: 17,
    color: 'black',
    marginVertical: 3,
  },
  oR: {
    color: 'red',
    fontSize: 16,
    fontWeight: 'bold',
    marginVertical: 3,
  },
  signInWith: {
    fontSize: 18,
    marginVertical: 3,
    fontWeight: '400',
    color: 'black',
  },
  socialMedia: {
    flex: 1,
    flexDirection: 'row',
    marginTop: 10,
    justifyContent: 'center',
  },
  icon: {
    height: 50,
    borderRadius: 13,
    backgroundColor: 'white',
    padding: 10,
    elevation: 20,
    margin: 10,
  },
  horizontalLine: {
    borderBottomColor: 'black',
    borderBottomWidth: 1,
    margin: 20,
  },
  signUp: {
    textAlign: 'center',
    color: 'black',
    fontSize: 18,
  },
  footer: {
    marginTop: 20,
  },
});
