import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    height: '100%',
    // marginTop: 3,
    backgroundColor: 'white',
    // backgroundColor: 'red',
    // borderWidth: 3,
    // borderColor: 'red',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    // borderWidth: 2,
    padding: 5,
    height: 45,
    alignItems: 'center',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    backgroundColor: 'white',
    elevation: 20,
    marginBottom: 5,
  },
  navIconContainer: {position: 'absolute', left: 7},
  headerLogoContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 200,
  },
  title: {
    fontSize: 30,
    fontWeight: '600',
    color: 'red',
  },
  profileIconContainer: {position: 'absolute', right: 7},
  searchBarContainer: {
    flexDirection: 'row',
    borderWidth: 2,
    borderColor: 'white',
    width: '90%',
    alignSelf: 'center',
    borderRadius: 20,
    marginVertical: 3,
    alignItems: 'center',
    height: 45,
    padding: 5,
    backgroundColor: 'white',
    elevation: 20,
    marginBottom: 5,
  },
  searchInput: {
    marginLeft: 20,
    width: '90%',
    fontSize: 20,
    textAlignVertical: 'center',
    height: 50,
  },
  categoryContainer: {
    // borderWidth: 3,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 20,
    elevation: 20,
    marginVertical: 5,
    backgroundColor: 'white',
    alignItems: 'center',
  },
  category: {
    fontSize: 25,
    fontWeight: '400',
    color: 'red',
    textAlign: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'red',
    marginBottom: 5,
  },
  categoryItemBox: {
    margin: 8,
    padding: 10,
    elevation: 20,
    backgroundColor: 'white',
    borderRadius: 15,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryItemTitle: {
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    margin: 5,
    color: 'black',
  },
  offerText: {
    fontSize: 30,
    fontWeight: '500',
    color: 'red',
    textAlign: 'center',
    borderBottomColor: 'red',
    marginBottom: 5,
  },
  offerSliderContainer: {
    width: '90%',
    margin: 10,
    alignSelf: 'center',
    // borderWidth: 3,
    borderRadius: 20,
    backgroundColor: 'white',
    elevation: 20,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sliderContainer: {},
  sliderImage: {height: '100%', width: '100%', borderRadius: 20},
  buttonText: {
    color: 'red',
    fontSize: 40,
    fontWeight: '800',
    borderRadius: 20,
    backgroundColor: 'white',
    height: 40,
    width: 40,
    lineHeight: 40,
    textAlign: 'center',
  },
});
